services:
  pgdb:
    image: 'postgres:17.5-alpine'
    container_name: pgdb 
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./postgres_db_backups:/db_backups
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev
    env_file:
     - .env
    ports:
      - "4000:8080"
    restart: unless-stopped


  thesis-server:
    container_name: thesis-server
    env_file:
     - .env
    build:
      context: .              
      dockerfile: Dockerfile.server
    ports:
      - "18080:8080"

  thesis-client:
    container_name: thesis-client
    env_file:
     - .env
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "18081:80"
