services:
  pgdb:
    image: 'postgres:17.7-alpine'
    container_name: pgdb 
    env_file:
      - .env
    ports:
      - "5144:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./postgres_db_backups:/db_backups
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always 
    
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: cile-keycloak
    command:
      - start-dev
    env_file:
     - .env
    ports:
      - "8081:8080"
    depends_on:
      pgdb:
        condition: service_healthy
    restart: always


  thesis-server:
    container_name: thesis-server
    env_file:
     - .env
    build:
      context: .              
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      pgdb:
        condition: service_healthy
    restart: always

  thesis-client:
    container_name: thesis-client
    env_file:
     - .env
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    restart: always    
