psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER ${KC_DB_USER} WITH ENCRYPTED PASSWORD '${KC_DB_PASSWORD}';
  CREATE USER ${THESIS_DB_USER} WITH ENCRYPTED PASSWORD '${THESIS_DB_PASSWORD}';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${KC_DB_NAME} OWNER ${KC_DB_USER};
  CREATE DATABASE ${THESIS_DB_NAME}  OWNER ${THESIS_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${KC_DB_NAME}" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${KC_DB_USER};
  GRANT ALL ON SCHEMA public TO ${KC_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${THESIS_DB_NAME}" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${THESIS_DB_USER};
  GRANT ALL ON SCHEMA public TO ${THESIS_DB_USER};
EOSQL
